// import { store } from 'quasar/wrappers'
import { createStore } from "vuex";
// import { st } from './st'
import { v4 as uuidv4 } from "uuid";

export default createStore({
  state: {
    products: [
      {
        id: uuidv4(),
        name: "BH Fitness F1 G6414V",
        category: "Беговая дорожка",
        oldprice: 64990,
        todayprice: 61990,
        type: "Электрическая",
        speed: 22,
        option: "Есть",
      },
      {
        id: uuidv4(),
        name: "BH Fitness F2 G6414V",
        category: "Беговая дорожка",
        oldprice: 64990,
        todayprice: 61990,
        type: "Электрическая",
        speed: 22,
        option: "Есть",
      },
      {
        id: uuidv4(),
        name: "BH Fitness F3 G6414V",
        category: "Беговая дорожка",
        oldprice: 64990,
        todayprice: 61990,
        type: "Электрическая",
        speed: 22,
        option: "Есть",
      },
      {
        id: uuidv4(),
        name: "BH Fitness F4 G6414V",
        category: "Беговая дорожка",
        oldprice: 64990,
        todayprice: 61990,
        type: "Электрическая",
        speed: 22,
        option: "Есть",
      },

    ],

    men: {
      breeches: [
        {
          id: uuidv4(),
          name: "Крутые бриджи",
          category: "Бриджи",
          oldprice: 2000,
          todayprice: 1599,
          option: "Есть",
        },
        {
          id: uuidv4(),
          name: "Крутые бриджи",
          category: "Бриджи",
          oldprice: 2300,
          todayprice: 1799,
          option: "Есть",
        },
        {
          id: uuidv4(),
          name: "Крутые бриджи",
          category: "Бриджи",
          oldprice: 2600,
          todayprice: 1999,
          option: "Есть",
        },
      ],
      headdress: [
        {
          id: uuidv4(),
          name: "Крутая кепка",
          category: "Кепка",
          oldprice: 2000,
          todayprice: 1599,
          option: "Есть",
        },
        {
          id: uuidv4(),
          name: "Крутая шляпа",
          category: "Шляпа",
          oldprice: 2000,
          todayprice: 1599,
          option: "Есть",
        },
        {
          id: uuidv4(),
          name: "Крутая панама",
          category: "Панама",
          oldprice: 2000,
          todayprice: 1599,
          option: "Есть",
        },
      ],
      shirts: [
        {
          id: uuidv4(),
          name: "Крутая рубашка",
          category: "Рубашка",
          oldprice: 2000,
          todayprice: 1599,
          option: "Есть",
        },
        {
          id: uuidv4(),
          name: "Крутая рубашка",
          category: "Рубашка",
          oldprice: 3000,
          todayprice: 2599,
          option: "Есть",
        },
        {
          id: uuidv4(),
          name: "Крутая рубашка",
          category: "Рубашка",
          oldprice: 2000,
          todayprice: 1899,
          option: "Есть",
        },
      ],
      t_shirts: [
        {
          id: uuidv4(),
          name: "Крутая футболка",
          category: "Футболка",
          oldprice: 2000,
          todayprice: 1899,
          option: "Есть",
        },
        {
          id: uuidv4(),
          name: "Крутая футболка",
          category: "Футболка",
          oldprice: 3000,
          todayprice: 2899,
          option: "Есть",
        },
        {
          id: uuidv4(),
          name: "Крутая футболка",
          category: "Футболка",
          oldprice: 1000,
          todayprice: 789,
          option: "Есть",
        },
      ],
      tights: [
        {
          id: uuidv4(),
          name: "Крутые тайтсы",
          category: "Тайтсы",
          oldprice: 2600,
          todayprice: 1999,
          option: "Есть",
        },
        {
          id: uuidv4(),
          name: "Крутые тайтсы",
          category: "Тайтсы",
          oldprice: 1600,
          todayprice: 1399,
          option: "Есть",
        },
        {
          id: uuidv4(),
          name: "Крутые тайтсы",
          category: "Тайтсы",
          oldprice: 1600,
          todayprice: 1199,
          option: "Есть",
        },
      ],
    },

    women: {
      headdress: [
        {
          id: uuidv4(),
          name: "Крутая кепка",
          category: "Кепка",
          oldprice: 2000,
          todayprice: 1599,
          option: "Есть",
        },
        {
          id: uuidv4(),
          name: "Крутая шляпа",
          category: "Шляпа",
          oldprice: 2000,
          todayprice: 1599,
          option: "Есть",
        },
        {
          id: uuidv4(),
          name: "Крутая панама",
          category: "Панама",
          oldprice: 2000,
          todayprice: 1599,
          option: "Есть",
        },
      ],
      leggings: [
        {
          id: uuidv4(),
          name: "Крутые легинсы",
          category: "Легинсы",
          oldprice: 2600,
          todayprice: 1999,
          option: "Есть",
        },
        {
          id: uuidv4(),
          name: "Крутые легинсы",
          category: "Легинсы",
          oldprice: 2700,
          todayprice: 2399,
          option: "Есть",
        },
        {
          id: uuidv4(),
          name: "Крутые легинсы",
          category: "Легинсы",
          oldprice: 1600,
          todayprice: 1299,
          option: "Есть",
        },
      ],
      polo: [
        {
          id: uuidv4(),
          name: "Крутое поло",
          category: "Голубое поло",
          oldprice: 1600,
          todayprice: 1299,
          option: "Есть",
        },
        {
          id: uuidv4(),
          name: "Крутое поло",
          category: "Зеленое поло",
          oldprice: 1600,
          todayprice: 1299,
          option: "Есть",
        },
        {
          id: uuidv4(),
          name: "Крутое поло",
          category: "Серое поло",
          oldprice: 1600,
          todayprice: 1299,
          option: "Есть",
        },
      ],
      swimsuit: [
        {
          id: uuidv4(),
          name: "Крутой купальник",
          category: "Купальник",
          oldprice: 1600,
          todayprice: 1299,
          option: "Есть",
        },
        {
          id: uuidv4(),
          name: "Крутой купальник",
          category: "Купальник",
          oldprice: 1800,
          todayprice: 1699,
          option: "Есть",
        },
        {
          id: uuidv4(),
          name: "Крутой купальник",
          category: "Купальник",
          oldprice: 2600,
          todayprice: 2299,
          option: "Есть",
        },
      ],
      trousers: [
        {
          id: uuidv4(),
          name: "Крутые брюки",
          category: "Брюки",
          oldprice: 2600,
          todayprice: 2299,
          option: "Есть",
        },
        {
          id: uuidv4(),
          name: "Крутые брюки",
          category: "Брюки",
          oldprice: 2700,
          todayprice: 2499,
          option: "Есть",
        },
        {
          id: uuidv4(),
          name: "Крутые брюки",
          category: "Брюки",
          oldprice: 2300,
          todayprice: 2000,
          option: "Есть",
        },
      ],
    },
  },
  getters: {
    PRODUCTS(state) {
      return state.products;
    },
  },
  mutations: {},
  actions: {},
  modules: {},
});
